config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'
  Spree::Core::Engine.routes.draw do
    namespace :admin do
      resources :orders, except: [:show] do
        resources :promotion_cashbacks do
          member do
            put 'change_state'
          end
        end
      end
    end
  end
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
  has_many :promotion_cashbacks, class_name: 'Spree::PromotionCashback', dependent: :destroy
end

app/models/spree/promotion/actions/create_promotion_cashback.rb
module Spree
  class Promotion
    module Actions
      class CreatePromotionCashback < Spree::PromotionAction

        include Spree::CalculatedAdjustments

        has_many :promotion_cashbacks, class_name: 'Spree::PromotionCashback', as: :promotion_action, dependent: :destroy

        before_validation -> { self.calculator ||= Calculator::FlatPercentItemTotal.new }

        def perform(payload = {})
          order = payload[:order]
          !!order.promotion_cashbacks.create(promotion_action: self)
        end

        def compute_amount(order)
          calculator.compute(order)
        end
      end
    end
  end
end

app/models/spree/promotion/actions/store_credit_adjustment.rb
module Spree
  class Promotion
    module Actions
      class StoreCreditAdjustment < Spree::PromotionAction

        include Spree::CalculatedAdjustments

        has_many :promotion_cashbacks, class_name: 'Spree::PromotionCashback', as: :promotion_action, dependent: :destroy

        before_validation -> { self.calculator ||= Calculator::FlatPercentItemTotal.new }

        def perform(payload = {})
          order = payload[:order]
          !!order.promotion_cashbacks.create(promotion_action: self)
        end
      end
    end
  end
end

app/models/spree/promotion_cashback.rb
module Spree
  class PromotionCashback < Spree::Base
    belongs_to :order, class_name: 'Spree::Order'
    belongs_to :promotion_action, polymorphic: true

    has_many :state_changes, as: :stateful

    scope :pending, -> { with_state('pending') }
    scope :completed, -> { with_state('completed') }
    scope :canceled, -> { with_state('canceled') }

    state_machine initial: :pending do

      event :complete do
        transition from: :pending, to: :completed
      end

      event :cancel do
        transition from: :pending, to: :canceled
      end

      before_transition to: :completed, do: :add_promotion_cashback

      after_transition do |promotion_cashback, transition|
        promotion_cashback.state_changes.create!(
          previous_state: transition.from,
          next_state:     transition.to,
          name:           'promotion_cashback',
        )
      end

    end

    def add_promotion_cashback
      Spree::StoreCredit.create(
            user: order.user,
            created_by: order.user,
            category_id: 1,
            currency: order.currency,
            amount: promotion_action.compute_amount(order)
          )
    end
  end
end

app/models/spree/promotion_handler/coupon_decorator.rb
Spree::PromotionHandler::Coupon.class_eval do
  def determine_promotion_application_result
    # Check for applied adjustments.
    discount = order.all_adjustments.promotion.eligible.detect do |p|
      p.source.promotion.code.try(:downcase) == order.coupon_code.downcase
    end

    # Check for applied line items or cashback added to wallet
    created_line_items = promotion.actions.detect do |a|
      a.type == 'Spree::Promotion::Actions::CreateLineItems' || a.type == 'Spree::Promotion::Actions::CreatePromotionCashback'
    end
    debugger
    if discount || created_line_items
      order.update_totals
      order.persist_totals
      set_success_code :coupon_code_applied
    else
      # if the promotion exists on an order, but wasn't found above,
      # we've already selected a better promotion
      if order.promotions.with_coupon_code(order.coupon_code)
        set_error_code :coupon_code_better_exists
      else
        # if the promotion was created after the order
        set_error_code :coupon_code_not_found
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/spree/admin/promotion_cashbacks_controller.rb
module Spree
  module Admin
    class PromotionCashbacksController < ResourceController

      belongs_to 'spree/order', find_by: :number
      before_action :load_promotion_cashback, only: :change_state

      def index
        @promotion_cashbacks = @order.promotion_cashbacks.order(created_at: :asc)
      end

      def change_state
        params[:accept] ? @promotion_cashback.complete : @promotion_cashback.cancel
      end

      private

        def load_promotion_cashback
          @promotion_cashback = parent.promotion_cashbacks.find(params[:id])
        end

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PromotionCashback</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spree/admin/promotion_cashbacks/_promotion_cashback.html.erb
<tr data-hook="adjustment_row">
  <td><%= promotion_cashback.promotion_action_type %></td>
  <td><%= promotion_cashback.promotion_action.type %></td>
  <td class="text-center"><%= promotion_cashback.promotion_action.calculator.compute(promotion_cashback.order).to_f %></td>
  <td class="text-center"><span class="label label-<%= promotion_cashback.state %>" data-hook="<%= promotion_cashback.id %>"><%= promotion_cashback.state %></td>
  <td class="actions actions-2 text-center" data-hook="<%= promotion_cashback.id %>">
    <% if promotion_cashback.state == 'pending' %>
      <%= link_to('accept', change_state_admin_order_promotion_cashback_path(promotion_cashback.order.number, promotion_cashback, accept: true), remote: true, method: :put) if can?(:edit, promotion_cashback) %>
      <%= link_to('reject', change_state_admin_order_promotion_cashback_path(promotion_cashback.order.number, promotion_cashback), remote: true, method: :put) if can?(:delete, promotion_cashback) %>
    <% end %>
  </td>
</tr>

app/views/spree/admin/promotion_cashbacks/_promotion_cashbacks_table.html.erb
<div class="panel-heading">
  <h3 class="panel-title"><%= Spree.t(:promotion_cashbacks) %></h3>
</div>

<table class="table table-bordered promotion_cashbacks" data-hook="promotion_cashbacks">
  <thead data-hook="promotion_cashback_head">
    <tr>
      <th><%= Spree.t(:type) %></th>
      <th><%= Spree.t(:action_type) %></th>
      <th class="text-center"><%= Spree.t(:amount) %></th>
      <th class="text-center"><%= Spree.t(:state) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "promotion_cashback", collection: @promotion_cashbacks %>
  </tbody>
</table>

app/views/spree/admin/promotion_cashbacks/change_state.js.erb
$('td[data-hook="<%= @promotion_cashback.id %>"]').html('');
$('td span[data-hook="<%= @promotion_cashback.id %>"]').html("<%= @promotion_cashback.state %>").addClass("label-<%= @promotion_cashback.state %>");

app/views/spree/admin/promotion_cashbacks/index.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: :promotion_cashbacks} %>

<% content_for :page_title do %>
   / <%= plural_resource_name(Spree::PromotionCashback) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to(Spree.t(:new_promotion_cashback), new_admin_order_promotion_cashback_url(@order), class: "btn-success", icon: 'add') if can? :create, Spree::PromotionCashback %>
<% end %>

<% if @promotion_cashbacks.present? %>
  <div class="panel panel-default">
    <%= render partial: 'promotion_cashbacks_table' %>
  </div>
<% else %>
  <div class="alert alert-warning">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::PromotionCashback)) %>
  </div>
<% end %>

<% if @order.can_add_coupon? %>
  <div class="well" data-hook="promotion_cashbacks_new_coupon_code">
    <div class="form-group">
      <%= text_field_tag "coupon_code", "", placeholder: Spree.t(:coupon_code), class: "form-control" %>
    </div>
    <%= button Spree.t(:add_coupon_code), 'plus', 'submit', id: "add_coupon_code" %>
  </div>
<% end %>

<%= javascript_tag do %>
  var order_number = '<%= @order.number %>';
<% end %>

<%= render partial: 'spree/admin/shared/order_summary' %>

app/views/spree/admin/promotions/actions/_create_promotion_cashback.html.erb
<div class="panel-body calculator-fields">
  <div class="row no-marginb">
    <div class="form-group col-md-6 no-marginb">
      <% field_name = "#{param_prefix}[calculator_type]" %>
      <%= label_tag field_name, Spree.t(:calculator) %>
      <%= select_tag field_name,
                    options_from_collection_for_select(Spree::Promotion::Actions::CreatePromotionCashback.calculators, :to_s, :description, promotion_action.calculator.type),
                    :class => 'type-select select2' %>
    </div>
    <% unless promotion_action.new_record? %>
      <div class="form-group col-md-6 no-marginb settings">
        <% promotion_action.calculator.preferences.keys.map do |key| %>
          <% field_name = "#{param_prefix}[calculator_attributes][preferred_#{key}]" %>
          <%= label_tag field_name, Spree.t(key.to_s) %>
          <%= preference_field_tag(field_name,
                                   promotion_action.calculator.get_preference(key),
                                   :type => promotion_action.calculator.preference_type(key)) %>
        <% end %>
        <%= hidden_field_tag "#{param_prefix}[calculator_attributes][id]", promotion_action.calculator.id %>
      </div>
    <% end %>
  </div>
  <% if promotion_action.calculator.respond_to?(:preferences) %>
    <div class="alert alert-info js-warning margint no-marginb">
      <%= Spree.t(:calculator_settings_warning) %>
    </div>
  <% end %>
</div>

app/views/spree/admin/shared/_order_tabs.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:orders), admin_orders_path %> /
  <%= link_to @order.number, spree.edit_admin_order_path(@order) %>
<% end %>

<% content_for :sidebar do %>
  <ul class="nav nav-pills nav-stacked" data-hook="admin_order_tabs">
    <% if ((can? :update, @order) && (@order.shipments.size.zero? || @order.shipments.shipped.size.zero?)) %>
      <li<%== ' class="active"' if current == :cart %> data-hook='admin_order_tabs_cart_details'>
        <%= link_to_with_icon 'edit', Spree.t(:cart), cart_admin_order_url(@order) %>
      </li>
    <% end %>

    <% if can?(:update, @order) && @order.checkout_steps.include?("address") %>
      <li<%== ' class="active"' if current == :customer_details %> data-hook='admin_order_tabs_customer_details'>
        <%= link_to_with_icon 'user', Spree.t(:customer), spree.admin_order_customer_url(@order) %>
      </li>
    <% end %>

    <% if can? :update, @order %>
      <li<%== ' class="active"' if current == :shipments %> data-hook='admin_order_tabs_shipment_details'>
        <%= link_to_with_icon 'road', Spree.t(:shipments), edit_admin_order_url(@order) %>
      </li>
    <% end %>

    <% if can? :index, Spree::Adjustment %>
      <li<%== ' class="active"' if current == :adjustments %> data-hook='admin_order_tabs_adjustments'>
        <%= link_to_with_icon 'wrench', Spree.t(:adjustments), spree.admin_order_adjustments_url(@order) %>
      </li>
    <% end %>

    <% if can? :index, Spree::PromotionCashback %>
      <li<%== ' class="active"' if current == :promotion_cashbacks %> data-hook='admin_order_tabs_promotion_cashbacks'>
        <%= link_to_with_icon 'wrench', Spree.t(:promotion_cashbacks), admin_order_promotion_cashbacks_url(@order) %>
      </li>
    <% end %>

    <% if can? :index, Spree::ReturnAuthorization %>
      <% if @order.completed? %>
        <li<%== ' class="active"' if current == :return_authorizations %> data-hook='admin_order_tabs_return_authorizations'>
          <%= link_to_with_icon 'transfer', Spree.t(:return_authorizations), spree.admin_order_return_authorizations_url(@order) %>
        </li>
      <% end %>
    <% end %>

    <% if can? :index, Spree::CustomerReturn %>
      <% if @order.completed? %>
        <li<%== ' class="active"' if current == :customer_returns %>>
          <%= link_to_with_icon 'transfer', Spree.t(:customer_returns), spree.admin_order_customer_returns_url(@order) %>
        </li>
      <% end %>
    <% end %>

    <% if can? :update, @order %>
      <li<%== ' class="active"' if current == :state_changes %> data-hook='admin_order_tabs_state_changes'>
        <%= link_to_with_icon 'refresh', Spree::StateChange.human_attribute_name(:state_changes), spree.admin_order_state_changes_url(@order) %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/spree/promotions/actions/_store_credit_adjustment.html.erb
<div class="panel-body calculator-fields">
  <div class="row no-marginb">
    <div class="form-group col-md-6 no-marginb">
      <% field_name = "#{param_prefix}[calculator_type]" %>
      <%= label_tag field_name, Spree.t(:calculator) %>
      <%= select_tag field_name,
                    options_from_collection_for_select(Spree::Promotion::Actions::StoreCreditAdjustment.calculators, :to_s, :description, promotion_action.calculator.type),
                    :class => 'type-select select2' %>
    </div>
    <% unless promotion_action.new_record? %>
      <div class="form-group col-md-6 no-marginb settings">
        <% promotion_action.calculator.preferences.keys.map do |key| %>
          <% field_name = "#{param_prefix}[calculator_attributes][preferred_#{key}]" %>
          <%= label_tag field_name, Spree.t(key.to_s) %>
          <%= preference_field_tag(field_name,
                                   promotion_action.calculator.get_preference(key),
                                   :type => promotion_action.calculator.preference_type(key)) %>
        <% end %>
        <%= hidden_field_tag "#{param_prefix}[calculator_attributes][id]", promotion_action.calculator.id %>
      </div>
    <% end %>
  </div>
  <% if promotion_action.calculator.respond_to?(:preferences) %>
    <div class="alert alert-info js-warning margint no-marginb">
      <%= Spree.t(:calculator_settings_warning) %>
    </div>
  <% end %>
</div>